class Solution {
public:
    string intToRoman(int n) {
        string ans;
        while(n>=1000)
        {
            n=n-1000;
            ans.push_back('M');
        }
        while(n>=900)
        {
            n=n-900;
            ans.push_back('C');
            ans.push_back('M');
        }
        while(n>=500)
        {
            n=n-500;
            ans.push_back('D');
        }
        while(n>=400)
        {
            n=n-400;
            ans.push_back('C');
            ans.push_back('D');
        }
        while(n>=100)
        {
            n=n-100;
            ans.push_back('C');
        }
        while(n>=90)
        {
            n=n-90;
            ans.push_back('X');
            ans.push_back('C');
        }
        while(n>=50)
        {
            n=n-50;
            ans.push_back('L');
        }
        while(n>=40)
        {
            n=n-40;
            ans.push_back('X');
            ans.push_back('L');
        }
        while(n>=10)
        {
            n=n-10;
            ans.push_back('X');
        }
        while(n>=9)
        {
            n=n-9;
            ans.push_back('I');
            ans.push_back('X');
        }
        while(n>=5)
        {
            n=n-5;
            ans.push_back('V');
        }
        while(n>=4)
        {
            n=n-4;
            ans.push_back('I');
            ans.push_back('V');
        }
        while(n>=1)
        {
            n=n-1;
            ans.push_back('I');
        }
        return ans;
    }
};